### ISSUE TITLE
Unintuitive cropper resizing behavior

### ISSUE THREAD

**Issue by kincaidoneil** [bytescale/bytescale-upload-widget#24]
I've been analyzing user sessions of uploading a profile photo & cropping it. Many users seem to resize the cropped region dramatically around/within the image, seemingly inadvertently.

Right now, dragging the cropped region to the edge of the image begins growing/shrinking the cropped region, which I believe breaks most users' expectations about its behavior.

Typically:
- Dragging the cropped region translates it within the image, but _doesn't_ resize it
- Only dragging the corner handles resizes the cropped region

Could you consider changing this behavior?

**Comment by ljwagerfield** [comment]
You can now set `allowResizeOnMove: false` to get the behaviour you desire:

[Bytescale Upload Widget (Configuration)](https://github.com/bytescale/bytescale-upload-widget?tab=readme-ov-file#%EF%B8%8F-configuration)

I hope that helps!

**Comment by kincaidoneil** [comment]
Perfect, thank you!
